# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84c0879a0384912e4ad3ec9bd224f111d692609a8c07064af56c26cbe6b4cc0f09db077a50cf9cd8db6cc682404208b1a3ad69a998dbe2c58cf79e1ae633dc8a

test:
  secret_key_base: 3de973b18e77698d76a7190dffb41837957472c3abdc494a2c5a8677cfd3e7e417ca14b854d0d0a04218a879768f4b2fe6ce3bd7a01f598f02474f1d73a00549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
